<x-app-layout>
<x-slot name="header"><div><div class="admin-kicker">Concursos y dinámicas</div><h1 class="admin-title">Crea experiencias que conectan</h1><p class="admin-subtitle">Publica preguntas en vivo, define la respuesta correcta y premia a tus escuchas.</p></div></x-slot>
@php($field='w-full rounded-xl border border-white/10 bg-zinc-950 px-4 py-3 text-sm text-white placeholder:text-zinc-600 focus:border-orange-500/50 focus:ring-orange-500/20')
<div class="admin-container space-y-7 py-7">
@if(session('success'))<div class="rounded-2xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-2xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200"><b>Revisa los datos.</b><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="admin-panel overflow-hidden">
<div class="border-b border-white/10 p-6"><div class="flex items-center gap-3"><div class="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-500 text-xl font-black text-black">+</div><div><h2 class="text-xl font-black text-white">Crear nueva dinámica</h2><p class="mt-1 text-sm text-zinc-500">Completa la información para publicar tu concurso.</p></div></div></div>
<form method="POST" action="{{ route('admin.contests.store') }}" enctype="multipart/form-data" class="space-y-6 p-6">@csrf
<div class="grid gap-5 lg:grid-cols-2"><label class="block"><span class="mb-2 block text-xs font-bold text-zinc-300">Nombre de la dinámica *</span><input name="title" value="{{ old('title') }}" required maxlength="140" placeholder="Ej. La trivia de Somos Radio" class="{{ $field }}"></label><label class="block"><span class="mb-2 block text-xs font-bold text-zinc-300">Estación</span><select name="station_id" class="{{ $field }}"><option value="">Todas / Somos Radio</option>@foreach($stations as $station)<option value="{{ $station->id }}">{{ $station->name }}</option>@endforeach</select></label></div>
<div class="grid gap-5 lg:grid-cols-[1fr_260px]"><label class="block"><span class="mb-2 block text-xs font-bold text-zinc-300">Pregunta *</span><textarea name="question" required rows="4" placeholder="Escribe aquí la pregunta que harás al aire..." class="{{ $field }}">{{ old('question') }}</textarea></label><label class="block"><span class="mb-2 block text-xs font-bold text-zinc-300">Imagen de la dinámica <span class="font-normal text-zinc-600">(opcional)</span></span><div class="flex h-[118px] cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-white/15 bg-zinc-950 px-4 text-center transition hover:border-orange-500/40"><span class="text-2xl">🖼️</span><span class="mt-1 text-xs font-bold text-zinc-300">Seleccionar imagen</span><span class="mt-1 text-[10px] text-zinc-600">JPG, PNG o WEBP · máx. 4 MB</span><input type="file" name="image" accept="image/jpeg,image/png,image/webp" class="mt-2 w-full text-[10px] text-zinc-500 file:hidden"></div></label></div>
<div><div class="mb-2 text-xs font-bold text-zinc-300">Opciones de respuesta *</div><div class="grid gap-3 lg:grid-cols-3">@foreach(['a'=>'A','b'=>'B','c'=>'C'] as $key=>$letter)<label class="flex items-center gap-3 rounded-xl border border-white/10 bg-zinc-950 px-3"><span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-white/20 text-xs font-black text-zinc-300">{{ $letter }}</span><input name="option_{{ $key }}" required placeholder="Opción {{ $letter }}" class="min-w-0 flex-1 border-0 bg-transparent py-3 text-sm text-white placeholder:text-zinc-600 focus:ring-0"></label>@endforeach</div></div>
<div class="grid gap-4 lg:grid-cols-3"><label><span class="mb-2 block text-xs font-bold text-zinc-300">Respuesta correcta *</span><select name="correct_option" required class="{{ $field }}"><option value="A">Opción A</option><option value="B">Opción B</option><option value="C">Opción C</option></select></label><label><span class="mb-2 block text-xs font-bold text-zinc-300">Número de ganadores *</span><input type="number" name="max_winners" value="1" min="1" required class="{{ $field }}"></label><label><span class="mb-2 block text-xs font-bold text-zinc-300">Premio</span><input name="prize" placeholder="Ej. Boletos, kit, mercancía..." class="{{ $field }}"></label></div>
<label class="block"><span class="mb-2 block text-xs font-bold text-zinc-300">Instrucciones para reclamar el premio</span><textarea name="redemption_instructions" rows="3" placeholder="Indica cómo pueden reclamar su premio..." class="{{ $field }}"></textarea></label>
<div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-2 block text-xs font-bold text-zinc-300">Fecha y hora de inicio</span><input type="datetime-local" name="starts_at" class="{{ $field }}"></label><label><span class="mb-2 block text-xs font-bold text-zinc-300">Fecha y hora de fin</span><input type="datetime-local" name="ends_at" class="{{ $field }}"></label></div>
<div class="flex flex-col gap-5 border-t border-white/10 pt-5 xl:flex-row xl:items-center xl:justify-between"><div class="flex flex-wrap gap-x-6 gap-y-3">@foreach([['is_active','Activar dinámica',false],['close_when_full','Cerrar al llenar ganadores',true],['auto_notify_winners','Avisar ganador automáticamente por push',false]] as [$name,$label,$checked])<label class="inline-flex cursor-pointer items-center gap-2 text-sm font-bold text-zinc-300"><input type="checkbox" name="{{ $name }}" value="1" @checked($checked) class="rounded border-white/20 bg-zinc-900 text-orange-500 focus:ring-orange-500/30">{{ $label }}</label>@endforeach</div><button class="admin-btn-primary whitespace-nowrap">Crear dinámica</button></div>
</form></section>
<section class="admin-panel overflow-hidden"><div class="flex flex-col gap-3 border-b border-white/10 p-6 sm:flex-row sm:items-end sm:justify-between"><div><div class="admin-kicker">Historial</div><h2 class="mt-1 text-xl font-black text-white">Dinámicas configuradas</h2><p class="mt-1 text-sm text-zinc-500">Consulta participantes, ganadores y estado de cada dinámica.</p></div><div class="rounded-xl border border-white/10 bg-zinc-950 px-4 py-2 text-xs text-zinc-500">{{ $contests->total() }} dinámica{{ $contests->total()==1?'':'s' }}</div></div>
<div class="divide-y divide-white/10">@forelse($contests as $contest)
<article class="p-5 transition hover:bg-white/[.02]"><div class="grid gap-5 lg:grid-cols-[96px_minmax(0,1fr)_auto] lg:items-center">
<div class="h-24 w-24 overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-orange-500/20 to-zinc-950">@if($contest->image_path)<img src="{{ asset('storage/'.$contest->image_path) }}" alt="" class="h-full w-full object-cover">@else<div class="flex h-full w-full flex-col items-center justify-center text-center"><span class="text-3xl">📻</span><span class="mt-1 px-2 text-[9px] font-black uppercase tracking-wider text-orange-300">Somos Radio</span></div>@endif</div>
<div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border px-2 py-1 text-[9px] font-black uppercase {{ $contest->is_active?'border-emerald-500/20 bg-emerald-500/10 text-emerald-300':'border-white/10 bg-white/5 text-zinc-500' }}">{{ $contest->is_active?'Activa':'Inactiva' }}</span><span class="rounded-full border border-orange-500/20 bg-orange-500/10 px-2 py-1 text-[9px] font-black text-orange-300">{{ $contest->station?->name ?? 'Todas' }}</span>@if($contest->auto_notify_winners)<span class="rounded-full border border-sky-500/20 bg-sky-500/10 px-2 py-1 text-[9px] font-black text-sky-300">Push auto</span>@endif</div><h3 class="mt-2 truncate text-lg font-black text-white">{{ $contest->title }}</h3><p class="mt-1 line-clamp-2 text-sm text-zinc-400">{{ $contest->question }}</p>@if($contest->starts_at || $contest->ends_at)<div class="mt-2 text-[11px] text-zinc-600">{{ $contest->starts_at?->format('d/m/Y H:i') ?? 'Ahora' }} → {{ $contest->ends_at?->format('d/m/Y H:i') ?? 'Sin fecha de fin' }}</div>@endif</div>
<div class="grid grid-cols-4 gap-5 text-center"><div><b class="text-base text-white">{{ $contest->entries_count }}</b><div class="text-[9px] uppercase text-zinc-600">Particip.</div></div><div><b class="text-base text-white">{{ $contest->correct_count }}</b><div class="text-[9px] uppercase text-zinc-600">Correctas</div></div><div><b class="text-base text-orange-300">{{ $contest->winners_count }}/{{ $contest->max_winners }}</b><div class="text-[9px] uppercase text-zinc-600">Ganadores</div></div><div><b class="text-base text-emerald-300">{{ $contest->claimed_count }}</b><div class="text-[9px] uppercase text-zinc-600">Canjeados</div></div></div></div>
<div class="mt-4 flex flex-wrap items-center gap-3 border-t border-white/10 pt-3"><a href="{{ route('admin.contests.entries',$contest) }}" class="rounded-lg bg-white/5 px-3 py-2 text-xs font-black text-orange-300 hover:bg-white/10">Ver participantes</a><form method="POST" action="{{ route('admin.contests.toggle',$contest) }}">@csrf @method('PATCH')<button class="rounded-lg px-3 py-2 text-xs font-black {{ $contest->is_active?'text-amber-300':'text-emerald-300' }} hover:bg-white/5">{{ $contest->is_active?'Desactivar':'Activar' }}</button></form><form method="POST" action="{{ route('admin.contests.destroy',$contest) }}" onsubmit="return confirm('¿Eliminar esta dinámica y sus participaciones?')">@csrf @method('DELETE')<button class="rounded-lg px-3 py-2 text-xs font-bold text-red-300 hover:bg-red-500/10">Eliminar</button></form></div></article>
@empty<div class="p-12 text-center text-zinc-500">Todavía no hay dinámicas.</div>@endforelse</div><div class="border-t border-white/10 p-5">{{ $contests->links() }}</div></section>
</div></x-app-layout>
