<x-app-layout>
<x-slot name="header"><div><div class="admin-kicker">Participación</div><h1 class="admin-title">Concursos y dinámicas</h1><p class="admin-subtitle">Publica preguntas en vivo, define la respuesta correcta y cuántos participantes pueden ganar.</p></div></x-slot>
<div class="admin-container space-y-7 py-7">
@if(session('success'))<div class="rounded-2xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-2xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200"><div class="font-black">Revisa los datos.</div><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="admin-panel p-6"><div class="admin-kicker">Nueva dinámica</div><h2 class="mt-1 text-xl font-black text-white">Crear concurso</h2>
<form method="POST" action="{{ route('admin.contests.store') }}" class="mt-5 space-y-4">@csrf
<div class="grid gap-4 lg:grid-cols-2"><input name="title" required maxlength="140" placeholder="Nombre de la dinámica" class="rounded-xl border-white/10 bg-zinc-950 text-white"><select name="station_id" class="rounded-xl border-white/10 bg-zinc-950 text-white"><option value="">Ambas estaciones</option>@foreach($stations as $station)<option value="{{ $station->id }}">{{ $station->name }}</option>@endforeach</select></div>
<textarea name="question" required rows="2" placeholder="Pregunta" class="w-full rounded-xl border-white/10 bg-zinc-950 text-white"></textarea>
<div class="grid gap-3 lg:grid-cols-3"><input name="option_a" required placeholder="Opción A" class="rounded-xl border-white/10 bg-zinc-950 text-white"><input name="option_b" required placeholder="Opción B" class="rounded-xl border-white/10 bg-zinc-950 text-white"><input name="option_c" required placeholder="Opción C" class="rounded-xl border-white/10 bg-zinc-950 text-white"></div>
<div class="grid gap-4 lg:grid-cols-3"><select name="correct_option" required class="rounded-xl border-white/10 bg-zinc-950 text-white"><option value="A">Correcta: A</option><option value="B">Correcta: B</option><option value="C">Correcta: C</option></select><input type="number" name="max_winners" value="1" min="1" required placeholder="Ganadores" class="rounded-xl border-white/10 bg-zinc-950 text-white"><input name="prize" placeholder="Premio" class="rounded-xl border-white/10 bg-zinc-950 text-white"></div>
<textarea name="redemption_instructions" rows="2" placeholder="Instrucciones para reclamar el premio" class="w-full rounded-xl border-white/10 bg-zinc-950 text-white"></textarea>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="text-xs text-zinc-500">Inicio</label><input type="datetime-local" name="starts_at" class="mt-1 w-full rounded-xl border-white/10 bg-zinc-950 text-white"></div><div><label class="text-xs text-zinc-500">Fin</label><input type="datetime-local" name="ends_at" class="mt-1 w-full rounded-xl border-white/10 bg-zinc-950 text-white"></div></div>
<div class="flex flex-wrap items-center justify-between gap-4"><div class="flex gap-5"><label class="text-sm font-bold text-white"><input type="checkbox" name="is_active" value="1" class="mr-2 text-orange-500">Activa</label><label class="text-sm font-bold text-white"><input type="checkbox" name="close_when_full" value="1" checked class="mr-2 text-orange-500">Cerrar al llenar ganadores</label></div><button class="admin-btn-primary">Crear dinámica</button></div>
</form></section>
<section><div class="mb-4"><div class="admin-kicker">Historial</div><h2 class="mt-1 text-xl font-black text-white">Dinámicas configuradas</h2></div><div class="space-y-3">
@forelse($contests as $contest)<article class="admin-panel p-5"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div class="flex gap-2"><span class="rounded-full border px-2 py-1 text-[9px] font-black uppercase {{ $contest->is_active ? 'border-emerald-500/20 bg-emerald-500/10 text-emerald-300':'border-white/10 text-zinc-500' }}">{{ $contest->is_active?'Activa':'Inactiva' }}</span><span class="rounded-full border border-orange-500/20 bg-orange-500/10 px-2 py-1 text-[9px] font-black text-orange-300">{{ $contest->station?->name ?? 'Ambas estaciones' }}</span></div><h3 class="mt-2 text-lg font-black text-white">{{ $contest->title }}</h3><p class="mt-1 text-sm text-zinc-400">{{ $contest->question }}</p></div><div class="grid grid-cols-4 gap-5 text-center"><div><b class="text-white">{{ $contest->entries_count }}</b><div class="text-[9px] text-zinc-600">PART.</div></div><div><b class="text-white">{{ $contest->correct_count }}</b><div class="text-[9px] text-zinc-600">CORR.</div></div><div><b class="text-orange-300">{{ $contest->winners_count }}/{{ $contest->max_winners }}</b><div class="text-[9px] text-zinc-600">GAN.</div></div><div><b class="text-emerald-300">{{ $contest->claimed_count }}</b><div class="text-[9px] text-zinc-600">CANJ.</div></div></div></div><div class="mt-4 flex gap-4 border-t border-white/10 pt-3"><a href="{{ route('admin.contests.entries',$contest) }}" class="text-xs font-black text-orange-300">Ver participantes</a><form method="POST" action="{{ route('admin.contests.destroy',$contest) }}" onsubmit="return confirm('¿Eliminar esta dinámica y sus participaciones?')">@csrf @method('DELETE')<button class="text-xs font-bold text-red-300">Eliminar</button></form></div></article>@empty<div class="admin-panel p-12 text-center text-zinc-500">Todavía no hay dinámicas.</div>@endforelse
</div><div class="mt-5">{{ $contests->links() }}</div></section>
</div></x-app-layout>
